// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type PrStatus string

const (
	PrStatusOPEN   PrStatus = "OPEN"
	PrStatusMERGED PrStatus = "MERGED"
)

func (e *PrStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PrStatus(s)
	case string:
		*e = PrStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PrStatus: %T", src)
	}
	return nil
}

type NullPrStatus struct {
	PrStatus PrStatus `json:"pr_status"`
	Valid    bool     `json:"valid"` // Valid is true if PrStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPrStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PrStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PrStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPrStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PrStatus), nil
}

type PrReviewer struct {
	PrID   uuid.UUID `json:"pr_id"`
	UserID uuid.UUID `json:"user_id"`
}

type PullRequest struct {
	ID        uuid.UUID          `json:"id"`
	Title     string             `json:"title"`
	AuthorID  uuid.UUID          `json:"author_id"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Team struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

type User struct {
	ID       uuid.UUID   `json:"id"`
	Name     string      `json:"name"`
	IsActive bool        `json:"is_active"`
	TeamID   pgtype.UUID `json:"team_id"`
}
