// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: query.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addReviewerToPR = `-- name: AddReviewerToPR :exec

INSERT INTO pr_reviewers (pr_id, user_id)
VALUES ($1, $2)
    ON CONFLICT (pr_id, user_id) DO NOTHING
`

type AddReviewerToPRParams struct {
	PrID   uuid.UUID `json:"pr_id"`
	UserID uuid.UUID `json:"user_id"`
}

// --- Reviewers ---
func (q *Queries) AddReviewerToPR(ctx context.Context, arg AddReviewerToPRParams) error {
	_, err := q.db.Exec(ctx, addReviewerToPR, arg.PrID, arg.UserID)
	return err
}

const createPullRequest = `-- name: CreatePullRequest :one

INSERT INTO pull_requests (title, author_id)
VALUES ($1, $2)
    RETURNING id, title, author_id, status, created_at, updated_at
`

type CreatePullRequestParams struct {
	Title    string    `json:"title"`
	AuthorID uuid.UUID `json:"author_id"`
}

// --- Pull Requests ---
func (q *Queries) CreatePullRequest(ctx context.Context, arg CreatePullRequestParams) (PullRequest, error) {
	row := q.db.QueryRow(ctx, createPullRequest, arg.Title, arg.AuthorID)
	var i PullRequest
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AuthorID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createTeam = `-- name: CreateTeam :one

INSERT INTO teams (name)
VALUES ($1)
    RETURNING id, name
`

// --- Teams ---
func (q *Queries) CreateTeam(ctx context.Context, name string) (Team, error) {
	row := q.db.QueryRow(ctx, createTeam, name)
	var i Team
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const createUser = `-- name: CreateUser :one

INSERT INTO users (name, team_id)
VALUES ($1, $2)
    RETURNING id, name, is_active, team_id
`

type CreateUserParams struct {
	Name   string      `json:"name"`
	TeamID pgtype.UUID `json:"team_id"`
}

// --- Users ---
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Name, arg.TeamID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.TeamID,
	)
	return i, err
}

const deactivateUsersByTeam = `-- name: DeactivateUsersByTeam :exec
UPDATE users
SET is_active = false
WHERE team_id = $1 AND is_active = true
`

func (q *Queries) DeactivateUsersByTeam(ctx context.Context, teamID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateUsersByTeam, teamID)
	return err
}

const getCandidatesForInitialReview = `-- name: GetCandidatesForInitialReview :many

SELECT id, name, is_active, team_id FROM users u1
WHERE
    team_id = (SELECT team_id FROM users u2 WHERE u2.id = $1)
  AND u1.is_active = true
  AND u1.id != $1
LIMIT 2
`

// --- основные запросы ---
func (q *Queries) GetCandidatesForInitialReview(ctx context.Context, id uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, getCandidatesForInitialReview, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsActive,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCandidatesForReassignment = `-- name: GetCandidatesForReassignment :many
SELECT id, name, is_active, team_id FROM users u1
WHERE
    team_id = (SELECT team_id FROM users u2 WHERE u2.id = $1)
  AND u1.is_active = true
  AND u1.id != $2
    AND u1.id NOT IN (
        SELECT)
LIMIT 5
`

type GetCandidatesForReassignmentParams struct {
	ID   uuid.UUID `json:"id"`
	ID_2 uuid.UUID `json:"id_2"`
}

func (q *Queries) GetCandidatesForReassignment(ctx context.Context, arg GetCandidatesForReassignmentParams) ([]User, error) {
	rows, err := q.db.Query(ctx, getCandidatesForReassignment, arg.ID, arg.ID_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsActive,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOpenPullRequestsForReviewer = `-- name: GetOpenPullRequestsForReviewer :many

SELECT pr.id, pr.title, pr.author_id, pr.status, pr.created_at, pr.updated_at
FROM pull_requests pr
         JOIN pr_reviewers prr ON pr.id = prr.pr_id
WHERE prr.user_id = $1 AND pr.status = 'OPEN'
`

// Возвращаем обновленный PR
func (q *Queries) GetOpenPullRequestsForReviewer(ctx context.Context, userID uuid.UUID) ([]PullRequest, error) {
	rows, err := q.db.Query(ctx, getOpenPullRequestsForReviewer, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PullRequest
	for rows.Next() {
		var i PullRequest
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.AuthorID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPullRequest = `-- name: GetPullRequest :one
SELECT id, title, author_id, status, created_at, updated_at FROM pull_requests
WHERE id = $1
`

func (q *Queries) GetPullRequest(ctx context.Context, id uuid.UUID) (PullRequest, error) {
	row := q.db.QueryRow(ctx, getPullRequest, id)
	var i PullRequest
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AuthorID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getReviewerCountForPR = `-- name: GetReviewerCountForPR :one
SELECT count(*) FROM pr_reviewers
WHERE pr_id = $1
`

func (q *Queries) GetReviewerCountForPR(ctx context.Context, prID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getReviewerCountForPR, prID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getReviewersForPR = `-- name: GetReviewersForPR :many
SELECT users.id, users.name, users.is_active, users.team_id
FROM users
         JOIN pr_reviewers ON users.id = pr_reviewers.user_id
WHERE pr_reviewers.pr_id = $1
`

func (q *Queries) GetReviewersForPR(ctx context.Context, prID uuid.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, getReviewersForPR, prID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsActive,
			&i.TeamID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeam = `-- name: GetTeam :one
SELECT id, name FROM teams
WHERE id = $1
`

func (q *Queries) GetTeam(ctx context.Context, id uuid.UUID) (Team, error) {
	row := q.db.QueryRow(ctx, getTeam, id)
	var i Team
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, name, is_active, team_id FROM users
WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsActive,
		&i.TeamID,
	)
	return i, err
}

const removeReviewerFromPR = `-- name: RemoveReviewerFromPR :exec
DELETE FROM pr_reviewers
WHERE pr_id = $1 AND user_id = $2
`

type RemoveReviewerFromPRParams struct {
	PrID   uuid.UUID `json:"pr_id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) RemoveReviewerFromPR(ctx context.Context, arg RemoveReviewerFromPRParams) error {
	_, err := q.db.Exec(ctx, removeReviewerFromPR, arg.PrID, arg.UserID)
	return err
}

const setUserActive = `-- name: SetUserActive :exec
UPDATE users
SET is_active = $2
WHERE id = $1
`

type SetUserActiveParams struct {
	ID       uuid.UUID `json:"id"`
	IsActive bool      `json:"is_active"`
}

func (q *Queries) SetUserActive(ctx context.Context, arg SetUserActiveParams) error {
	_, err := q.db.Exec(ctx, setUserActive, arg.ID, arg.IsActive)
	return err
}

const updatePullRequestStatus = `-- name: UpdatePullRequestStatus :one
UPDATE pull_requests
SET status = $2, updated_at = NOW()
WHERE id = $1
    RETURNING id, title, author_id, status, created_at, updated_at
`

type UpdatePullRequestStatusParams struct {
	ID     uuid.UUID `json:"id"`
	Status string    `json:"status"`
}

func (q *Queries) UpdatePullRequestStatus(ctx context.Context, arg UpdatePullRequestStatusParams) (PullRequest, error) {
	row := q.db.QueryRow(ctx, updatePullRequestStatus, arg.ID, arg.Status)
	var i PullRequest
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.AuthorID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
